### ISSUE TITLE
The comment in ExecuteOperationMetadata.digest_function seems wrong

### ISSUE THREAD

**Issue by stepinto** [bazelbuild/remote-apis#319] opened 2024-11-19 08:16 UTC
```
  // The digest function that was used to compute the action digest.
  //
  // If the digest function used is one of BLAKE3, MD5, MURMUR3, SHA1,
  // SHA256, SHA256TREE, SHA384, SHA512, or VSO, the server MAY leave
  // this field unset. In that case the client SHOULD infer the digest
  // function using the length of the action digest hash and the digest
  // functions announced in the server's capabilities.
  DigestFunction.Value digest_function = 6;
```
This [comment](https://github.com/bazelbuild/remote-apis/blob/253013303c9e1d52ebdeb5a3f0f869919e882f20/build/bazel/remote/execution/v2/remote_execution.proto#L1563) seems to be wrong.  Both BLAKE3 and SHA256 are 32-byte long.  So the client cannot distinguish them by just looking at the length of the digest.

**Comment by EdSchouten** [comment] 2024-11-19 10:02
Closing, as it is a duplicate of #312

**Closed by EdSchouten** 2024-11-19 10:02 UTC
